id: I44BA3266
default_language: en
source: ''
initial_creation_type: tmx
imported: 2022-12-14 14:36:04.848975+00:00
last_modified: 2022-12-14 14:36:04.848983+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-04-10T04:55:38.201Z'
  creationid: celso
  eft-text-id: UT22084-089-001
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_544-Siddhaikavira-v1
bases:
  '5757':
    source_metadata: null
    order: 1
    base_file: 5757.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
